/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis 
 * Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 27-Oct-2025 15:12:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 17
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

#define N 17
const float h[N] = 
{
  -0.0022809934f, -0.0181457014f, -0.0366734405f, -0.0448007377f,
  -0.0190996351f,  0.0509613997f,  0.1499422613f,  0.2382839426f,
   0.2737634095f,  0.2382839426f,  0.1499422613f,  0.0509613997f,
  -0.0190996351f, -0.0448007377f, -0.0366734405f, -0.0181457014f,
  -0.0022809934f
};
