/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis 
 * Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 27-Oct-2025 15:12:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 26
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

#define FS_ADC 12000
#define N 26
const float h[N] = 
{
  0.0009219922358,  0.00335702789, 0.006668464281, 0.007552863564,  0.00103278039,
   -0.01547866594, -0.03695775568, -0.04899393767, -0.03326134011,  0.02089643851,
     0.1057718769,    0.194080919,   0.2505506277,   0.2505506277,    0.194080919,
     0.1057718769,  0.02089643851, -0.03326134011, -0.04899393767, -0.03695775568,
   -0.01547866594,  0.00103278039, 0.007552863564, 0.006668464281,  0.00335702789,
  0.0009219922358
};
