/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 27-Oct-2025 15:12:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 17
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /home/vito/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
#define N 17
const double h[N] = 
{
  -0.002280993419638, -0.01814570140142, -0.03667344052183, -0.04480073772215,
   -0.01909963512648,  0.05096139974481,   0.1499422613724,   0.2382839426657,
     0.2737634095179,   0.2382839426657,   0.1499422613724,  0.05096139974481,
   -0.01909963512648, -0.04480073772215, -0.03667344052183, -0.01814570140142,
  -0.002280993419638
};
